minor patches
brainelectronics/micropython-winbond pull request #9
Opened 2023-11-15 15:40 UTC by hstarmans

as outlined in https://github.com/brainelectronics/micropython-winbond/issues/8

Thanks for this great library! Helped me a lot.
I think the following could be done to make it even better.
I already added my suggested improvements.

**change await function**
```python
# last bit (1) is BUSY bit in stat. reg. byte (0 = not busy, 1 = busy)
trials = 0
while 0x1 & self.spi.read(1, 0xFF)[0]:
    trials += 1
    if trials > 20:
         raise Exception("Can't read from device")
    sleep(0.1)
```
Current code can lead to infinite loop and you should do somethingl like above

**writeblocks should not check block length**
You check block length and raise warning if not satisfied.
This is against spec (https://docs.micropython.org/en/latest/library/os.html).
Also gives issue if you write a file raw to memory with a size not equal to multiple of blocks
```python
if len(buf) %buffsize != 0:
    buf += bytearray((buffsize-(len(buf)&buffsize))*[255])
```
**don't break just raise warning**
I would do something like this in the identify function.
```python
if mf != 0xEF or mem_type not in [0x40, 0x60, 0x70]:
    # Winbond manufacturer, Q25 series memory (tested 0x40 only)
    print(f"manufacturer ({}) or memory type ({}) note tested")
```

2023-11-15 16:02 UTC, brainelectronics commented
Thank you for your contribution @hstarmans 

I haven't yet updated this package with the latest contribution requirements/guidelines as done [here in the package template](https://micropython-package-template.readthedocs.io/en/latest/CONTRIBUTING.html)

May you could update the `changelog.md` and the `winbond/version.py` file?

2023-11-15 16:13 UTC, hstarmans commented
Added changes as requested!

2023-11-15 16:25 UTC, brainelectronics requested changes
Nice, we're almost there. Just the `flake8` style warnings need to be fixed

https://github.com/brainelectronics/micropython-winbond/actions/runs/6879924548/job/18713355483#step:5:1

2023-11-16 16:28 UTC, hstarmans commented
Sure, I added a config for pre-commit so a check is carried by git before a push is made to the repo. This is also recommended by micropython. The config is minimal. For a more extended example see https://github.com/sktime/sktime/blob/main/.pre-commit-config.yaml .

2023-11-16 16:34 UTC, merged